### ISSUE TITLE
转录失败

### ISSUE THREAD

**Issue by jeron-lgy** [WEIFENG2333/VideoCaptioner#1015]
### 问题描述 | Problem Description

5090转录失败  下载了最新的 wisper模型手动替换出现的日志错误

时间：2026-02-25 10:43:30.604705
开始转换音频
转换为音频执行命令: ffmpeg -i D:\111\铁甲小宝 - S01E04 - 第 4 集.mkv -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\xianka\AppData\Local\Temp\tmpqfcza9_0.wav
视频时长: 1344.24秒
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v3-turbo --print_progress --model_dir C:\Users\xianka\AppData\Local\VideoCaptioner\AppData\models C:\Users\xianka\AppData\Local\Temp\bk_asr\tmpb26ba6rw\audio.wav -l ja -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.4 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Starting to process: C:\Users\xianka\AppData\Local\Temp\bk_asr\tmpb26ba6rw\audio.wav
Starting sequential faster-whisper inference.
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2324, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2191, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-42108:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2026-02-25 10:43:41 - faster_whisper - ERROR - Faster Whisper 错误: 
2026-02-25 10:43:41 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "C:\Users\xianka\AppData\Local\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "C:\Users\xianka\AppData\Local\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xianka\AppData\Local\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xianka\AppData\Local\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError

### 日志信息（可选）| Logs (Optional)

```shell

```

**Comment by jeron-lgy** [comment]
#814 已解决

**Comment by dinghaisi064-spec** [comment]
为什么我在Faster-Whisper-XXL的目录里找不到app\core\bk_asr\faster_whisper.py这个文件呢？

**Comment by philpw99** [comment]
因为它确实不在这个目录里面。

**Comment by hhl2024** [comment]
你好，我换了50系显卡后，也是转录失败，请问怎么解决哈
