### ISSUE TITLE
50系显卡使用FasterWhisper Large V2模型转录时提示转录失败

### ISSUE THREAD

**Issue by yunchen1987** [WEIFENG2333/VideoCaptioner#443]
### 🤔 问题描述 Problem Description

以下为日志，FasterWhisper是用pip安装后发现软件自带下载然后又用pip卸载了，求教错误原因，感谢。
===========转录任务开始===========
时间：2025-03-07 22:49:31.592376
开始转换音频
转换为音频执行命令: ffmpeg -i F:\1.mp3 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\yunch\AppData\Local\Temp\tmpz6c1m7yz.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir C:\Users\yunch\AppData\Local\VideoCaptioner\AppData\models C:\Users\yunch\AppData\Local\Temp\bk_asr\tmp2arfu90j\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 90 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\yunch\AppData\Local\Temp\bk_asr\tmp2arfu90j\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-25880:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-03-07 22:49:47 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-03-07 22:49:47 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "C:\Users\yunch\AppData\Local\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "C:\Users\yunch\AppData\Local\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yunch\AppData\Local\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yunch\AppData\Local\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError

**Comment by philpw99** [comment]
#436 
类似的问题，应该还是Faster-Whisper-XXL的python版本没有卸载而导致的。
可以去命令行屏幕打入 `faster-whisper-xxl` 看看这命令还执行不，如果还能执行，说明没有卸载掉。

**Comment by yunchen1987** [comment]
> [#436](https://github.com/WEIFENG2333/VideoCaptioner/issues/436) 类似的问题，应该还是Faster-Whisper-XXL的python版本没有卸载而导致的。 可以去命令行屏幕打入 `faster-whisper-xxl` 看看这命令还执行不，如果还能执行，说明没有卸载掉。

感谢回复，已经通过pip命令卸载，并且试过命令行已经不能执行了，但目前仍会报错。是否需要把系统变量里的python文件夹删除？还是需要重启系统再试试？

**Comment by philpw99** [comment]
我明白了，Faster-Whisper-XXL.exe 本身里面有python，因此出错时会显示出`D:\whisper-fast-XXL_main_.py`这样的东西。
看来是CUDA的问题，建议去下载CUDA Toolkit 看看能不能修好：
https://developer.nvidia.com/cuda-downloads

**Comment by yunchen1987** [comment]
> 我明白了，Faster-Whisper-XXL.exe 本身里面有python，因此出错时会显示出`D:\whisper-fast-XXL_main_.py`这样的东西。 看来是CUDA的问题，建议去下载CUDA Toolkit 看看能不能修好： https://developer.nvidia.com/cuda-downloads 我用的也是12.8，这个版本应该没问题的。 当然， Faster-Whisper-XXL.exe 里面用的是自带的pytorch 2.2.2+cu121 ，这个一般来说应该没什么问题，5080是可以用的。

感谢回复，目前下载了最新版本的CUDA Toolkit，安装后运行程序仍报错，历史记录内容同上。

**Comment by philpw99** [comment]
倒不如直接去FasterWhisperXXL的源头，下载最新版本
https://github.com/Purfview/whisper-standalone-win/releases

然后直接跑faster-whisper-xxl.exe，让它转译个音频看看还会不会出错。

**Comment by yunchen1987** [comment]
> 倒不如直接去FasterWhisperXXL的源头，下载最新版本 https://github.com/Purfview/whisper-standalone-win/releases
> 
> 然后直接跑faster-whisper-xxl.exe，让它转译个音频看看还会不会出错。

试完了，报错信息一样，还是RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED

**Comment by philpw99** [comment]
看来你的问题也是和他们一样的：
https://github.com/Purfview/whisper-standalone-win/issues/403

**Comment by philpw99** [comment]
那你可以先去`app\core\bk_asr\faster_whisper.py`里面105行开始的命令里面加入这个 `--compute_type`的指令。

**Comment by yunchen1987** [comment]
> 那你可以先去`app\core\bk_asr\faster_whisper.py`里面105行开始的命令里面加入这个 `--compute_type`的指令。

感谢，已添加指令，现在可以直接运行了。^_^

**Comment by abc3636363** [comment]
请问我的显卡是AMD的RX2048，CUDA和我这个显卡是不是不同个东西来着，是不是起不到作用？我也是用CPU才能转录，CUDA不行

**Comment by philpw99** [comment]
使用AMD显卡的朋友可以尝试一下使用我的分支：
https://github.com/philpw99/VideoCaptioner/releases

里面虽然还是不能使用 FasterWhisper ，但可以使用 Vulkan 版的 Whisper CPP 来进行转录。
WhisperCPP 也可以使用 Whisper 的各种模型。

**Comment by aaron-nerv** [comment]
> > 那你可以先去`app\core\bk_asr\faster_whisper.py`里面105行开始的命令里面加入这个 `--compute_type`的指令。
> 
> 感谢，已添加指令，现在可以直接运行了。^_^
> 
> 折腾是值得的，CUDA转的比CPU可快太多了。

5070ti转录遇到一样的问题了，看不懂代码的萌新弱弱问一句这里要怎么添加呀

   ```
 def _build_command(self, audio_path: str) -> List[str]:
        """构建命令行参数"""

        cmd = [
            str(self.faster_whisper_program),
            "-m",
            str(self.model_path),
            # "--verbose", "true",
            "--print_progress",
        ]
```

**Comment by yunchen1987** [comment]
> > > 那你可以先去`app\core\bk_asr\faster_whisper.py`里面105行开始的命令里面加入这个 `--compute_type`的指令。
> > 
> > 
> > 感谢，已添加指令，现在可以直接运行了。^_^
> > 折腾是值得的，CUDA转的比CPU可快太多了。
> 
> 5070ti转录遇到一样的问题了，看不懂代码的萌新弱弱问一句这里要怎么添加呀
> 
> ```
> def _build_command(self, audio_path: str) -> List[str]:
>      """构建命令行参数"""
> 
>      cmd = [
>          str(self.faster_whisper_program),
>          "-m",
>          str(self.model_path),
>          # "--verbose", "true",
>          "--print_progress",
>      ]
> ```
我这会儿在单位先凭印象说一下我怎么加的，我是加到187行的提示音指令后面了，加完以后前后文如下，运行着是正常的，你先试试，不行的话我晚上回家后把家里的文件上传上来。
        # 完成的提示音
        cmd.extend(["--beep_off"])

        # compute_type参数
        cmd.extend(["--compute_type","float32"])

        return cmd

**Comment by aaron-nerv** [comment]
> 我这会儿在单位先凭印象说一下我怎么加的，我是加到187行的提示音指令后面了，加完以后前后文如下，运行着是正常的，你先试试，不行的话我晚上回家后把家里的文件上传上来。
> 
> ```
>     # 完成的提示音
>     cmd.extend(["--beep_off"])
> 
>     # compute_type参数
>     cmd.extend(["--compute_type","float32"])
> 
>     return cmd
> ```

感谢，加上以后运行成功了

**Comment by philpw99** [comment]
[据说](https://github.com/philpw99/VideoCaptioner/issues/44)去下载最新的r245.4下来，覆盖原来的 "Faster-Whisper-XXL" 目录就好了。
https://github.com/Purfview/whisper-standalone-win/releases

**Comment by littlenick123** [comment]
> 那你可以先去`app\core\bk_asr\faster_whisper.py`里面105行开始的命令里面加入这个 `--compute_type`的指令。

你好，可以告诉我添加在哪里吗？
下面是从105开始的代码：
def _build_command(self, audio_path: str) -> List[str]:
        """构建命令行参数"""

        cmd = [
            str(self.faster_whisper_program),
            "-m",
            str(self.model_path),
            # "--verbose", "true",
            "--print_progress",
        ]

        # 添加模型目录参数
        if self.model_dir:
            cmd.extend(["--model_dir", str(self.model_dir)])

        # 基本参数
        cmd.extend(
            [
                str(audio_path),
                "-l",
                self.language,
                "-d",
                self.device,
                "--output_format",
                self.output_format,
            ]
        )

**Comment by littlenick123** [comment]
> 按照yunchen1987的做法，原本是：
> 
> ```
>     # 完成的提示音
>     cmd.extend(["--beep_off"])
> 
>     return cmd
> ```
> 
> 改成：
> 
> ```
>     # 完成的提示音
>     cmd.extend(["--beep_off"])
> 
>     # compute_type参数
>     cmd.extend(["--compute_type","float32"])
> 
>     return cmd
> ```

我添加了这行代码后运行提示：
2025-05-22 00:55:11 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmp997m27h5\audio.srt
Traceback (most recent call last):
  File "D:\AppData\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmp997m27h5\audio.srt

然后我手动创建了一个tmp997m27h5文件夹，再运行没提示没有文件夹的错误了，但是又变成了：
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m tiny --print_progress --model_dir D:\AppData\VideoCaptioner\AppData\models C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmpfh7h6ee8\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 90 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmpfh7h6ee8\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-23228:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-05-22 01:01:06 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-05-22 01:01:06 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\AppData\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    logger.info("Faster Whisper 返回值: %s", self.process.returncode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError

**Comment by philpw99** [comment]
很奇怪，如果真的添加命令后，那么出来的日志里面在“--beep_off” 后面应该就有 "--compute_type float32" 的参数，但是日志里面没有，而且模型是tiny，也是不对的。

可能你还有做 #436 的修复。

**Comment by littlenick123** [comment]
> 很奇怪，如果真的添加命令后，那么出来的日志里面在“--beep_off” 后面应该就有 "--compute_type float32" 的参数，但是日志里面没有，而且模型是tiny，也是不对的。
> 
> 可能你还有做 [#436](https://github.com/WEIFENG2333/VideoCaptioner/issues/436) 里面[AetherKong](https://github.com/AetherKong)说的修复。

前面的是忘记换模型了，但是我换了largr-v2模型后还是错误，请大佬再帮忙分析分析，我也尝试了你上面提及的[AetherKong](https://github.com/AetherKong)说的修复。：
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir D:\AppData\VideoCaptioner\AppData\models C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmpqbraueu1\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 90 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\Nickxxx\AppData\Local\Temp\bk_asr\tmpqbraueu1\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-25520:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-05-25 00:59:24 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-05-25 00:59:24 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\AppData\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppData\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 269, in _run
    raise RuntimeError(error_msg)
RuntimeError

**Comment by markbex** [comment]
gpu rtx5070 ,转2个小时的音频，输出只有20句话，很奇怪。 用cpu就正常，用的是faster whisper GUI 0.85

**Comment by Ephemeralwanning** [comment]
```
===========转录任务开始===========
时间：2025-06-21 21:25:39.299500
开始转换音频
转换为音频执行命令: ffmpeg -i F:\Downloads\_ndm_downloads\Video\美国制裁华为.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\me\AppData\Local\Temp\tmpfewuphsu.wav
视频时长: 300.1秒
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir D:\solftwares\solftware\VideoCaptioner\AppData\models C:\Users\me\AppData\Local\Temp\bk_asr\tmpw8xswm30\audio.wav -l ja -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v5 --ff_mdx_kim2 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Audio filtering is in progress...
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 0/20 | 00:00<<?
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 1/20 | 00:11<<03:45
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 2/20 | 00:12<<01:32
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 3/20 | 00:12<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 4/20 | 00:13<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 5/20 | 00:13<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 6/20 | 00:14<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 7/20 | 00:14<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 8/20 | 00:14<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 9/20 | 00:15<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 10/20 | 00:15<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 11/20 | 00:16<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 12/20 | 00:16<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 13/20 | 00:17<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 14/20 | 00:17<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 15/20 | 00:18<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 16/20 | 00:18<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 17/20 | 00:18<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 18/20 | 00:19<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 19/20 | 00:19<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 20/20 | 00:20<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 20/20 | 00:20<<00:00
Starting sequential inference to transcribe: C:\Users\me\AppData\Local\Temp\bk_asr\tmpw8xswm30\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-89128:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-06-21 21:26:09 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\me\AppData\Local\Temp\bk_asr\tmpw8xswm30\audio.srt
Traceback (most recent call last):
  File "D:\solftwares\solftware\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
    raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\me\AppData\Local\Temp\bk_asr\tmpw8xswm30\audio.srt

===========转录任务开始===========
时间：2025-06-21 21:26:32.940399
开始转换音频
转换为音频执行命令: ffmpeg -i F:\Downloads\_ndm_downloads\Video\美国制裁华为.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\me\AppData\Local\Temp\tmps5yvozkm.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir D:\solftwares\solftware\VideoCaptioner\AppData\models C:\Users\me\AppData\Local\Temp\bk_asr\tmpb5_sy880\audio.wav -l ja -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v5 --ff_mdx_kim2 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Audio filtering is in progress...
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 0/20 | 00:00<<?
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 1/20 | 00:12<<03:51
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 2/20 | 00:12<<01:34
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 3/20 | 00:13<<00:51
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 4/20 | 00:13<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 5/20 | 00:13<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 6/20 | 00:14<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 7/20 | 00:14<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 8/20 | 00:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 9/20 | 00:15<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 10/20 | 00:15<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 11/20 | 00:16<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 12/20 | 00:16<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 13/20 | 00:17<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 14/20 | 00:17<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 15/20 | 00:18<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 16/20 | 00:18<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 17/20 | 00:18<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 18/20 | 00:19<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 19/20 | 00:19<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 20/20 | 00:20<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 20/20 | 00:20<<00:00
Starting sequential inference to transcribe: C:\Users\me\AppData\Local\Temp\bk_asr\tmpb5_sy880\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-90080:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-06-21 21:27:03 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\me\AppData\Local\Temp\bk_asr\tmpb5_sy880\audio.srt
Traceback (most recent call last):
  File "D:\solftwares\solftware\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\solftwares\solftware\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
    raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\me\AppData\Local\Temp\bk_asr\tmpb5_sy880\audio.srt
```


我也一样5080显卡，还是没看明白如何解决这个问题

**Comment by Ephemeralwanning** [comment]
已经解决，加入代码`cmd.extend(["--compute_type","float32"])`就行
![Image](https://github.com/user-attachments/assets/e1f0cb98-e4e4-4190-9c32-47f0d194b35b)

**Comment by wzxnb2333** [comment]
你好对于50系显卡可以直接写死（例如固定使用 float32）
直接在faster_whisper.py中修改105行整段
def _build_command(self, audio_path: str) -> List[str]:
    """构建命令行参数"""

    cmd = [
        str(self.faster_whisper_program),
        "-m",
        str(self.model_path),
        # "--verbose", "true",
        "--print_progress",
    ]

    # 添加模型目录参数
    if self.model_dir:
        cmd.extend(["--model_dir", str(self.model_dir)])

    # 基本参数
    cmd.extend(
        [
            str(audio_path),
            "-l",
            self.language,
            "-d",
            self.device,
            "--output_format",
            self.output_format,
        ]
    )

    # 直接写死为 float32
    cmd.extend(["--compute_type", "float32"])

    # 输出目录
    if self.output_dir:
        cmd.extend(["-o", str(self.output_dir)])
    else:
        cmd.extend(["-o", "source"])

    # VAD 相关参数
    if self.vad_filter:
        cmd.extend(
            [
                "--vad_filter",
                "true",
                "--vad_threshold",
                f"{self.vad_threshold:.2f}",
            ]
        )
        if self.vad_method:
            cmd.extend(["--vad_method", self.vad_method])
    else:
        cmd.extend(["--vad_filter", "false"])

    # 人声分离
    if self.ff_mdx_kim2 and self.faster_whisper_program.startswith("faster-whisper-xxl"):
        cmd.append("--ff_mdx_kim2")

    # 文本处理参数
    if self.one_word:
        self.one_word = 1
    else:
        self.one_word = 0
    if self.one_word in [0, 1, 2]:
        cmd.extend(["--one_word", str(self.one_word)])

    if self.sentence:
        cmd.extend(
            [
                "--sentence",
                "--max_line_width",
                str(self.max_line_width),
                "--max_line_count",
                str(self.max_line_count),
                "--max_comma",
                str(self.max_comma),
                "--max_comma_cent",
                str(self.max_comma_cent),
            ]
        )

    # 提示词
    if self.prompt:
        cmd.extend(["--prompt", self.prompt])

    # 完成的提示音
    cmd.extend(["--beep_off"])

    return cmd

**Comment by XiaoXiaoXian** [comment]
我也遇到同样的问题,GPU 是rtx5060TI 16G,
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:42:46_Pacific_Standard_Time_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

错误日志如下:

===========转录任务开始===========
时间：2025-08-04 23:14:00.205590
开始转换音频
转换为音频执行命令: ffmpeg -i VideoCaptioner\work-dir\11\111.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y AppData\Local\Temp\2\tmprscq0v4t.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m tiny --print_progress --model_dir VideoCaptioner\AppData\models AppData\Local\Temp\2\bk_asr\tmp4icjavqz\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 90 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: AppData\Local\Temp\2\bk_asr\tmp4icjavqz\audio.wav
Traceback (most recent call last):
File "whisper-fast-XXL_main_.py", line 2245, in
File "whisper-fast-XXL_main_.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-7284:ERROR] Failed to execute script 'main' due to unhandled exception!
Faster Whisper 返回值: 1
2025-08-04 23:14:04 - faster_whisper - ERROR - Faster Whisper 错误:
2025-08-04 23:14:04 - transcript_thread - ERROR - 转录过程中发生错误:
Traceback (most recent call last):
File "VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
asr_data = transcribe(
^^^^^^^^^^^
File "VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
asr_data = asr.run(callback=callback)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
resp_data = self._run(callback, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
raise RuntimeError(error_msg)
RuntimeError

**Comment by WEIFENG2333** [comment]
50系显卡转录错误的问题，接下来的1.4 版本将修复。

**Comment by upcwayne** [comment]
遇到一样的问题
