### ISSUE TITLE
50系显卡无法正常使用(已找到临时解决方案)

### ISSUE THREAD

**Issue by CoolJerryy** [WEIFENG2333/VideoCaptioner#714]
### 问题描述 | Problem Description

50系显卡在使用faster-whisper，large-v2模型时，提示转录失败

（先贴一下我的临时解决方案）
在VideoCaptioner\app\core\bk_asr\faster_whisper.py这个文件中
找到这个函数：def _build_command(self, audio_path: str) -> List[str]:
然后在最后return cmd之前加上一行代码：cmd.extend(["--compute_type","float16"])
```python
    def _build_command(self, audio_path: str) -> List[str]:
        """构建命令行参数"""
     
        #【此处省略若干代码】

        # 提示词
        if self.prompt:
            cmd.extend(["--prompt", self.prompt])

        # 完成的提示音
        cmd.extend(["--beep_off"])

        cmd.extend(["--compute_type","float16"])   #新增的代码在这★

        return cmd
``` 
然后就可以正常使用了

（解决方案来源）
查阅了faster-whisper的这一篇：https://github.com/SYSTRAN/faster-whisper/issues/1260
增加--compute_type float16 指令就能正常运行

（报错时的日志）
时间：2025-07-23 07:24:06.320901
开始转换音频
转换为音频执行命令: ffmpeg -i O:\LAN\File_Jerry\Phone_backup\直播录屏\SVID_20230821_142025_9.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\Jerry\AppData\Local\Temp\tmpl1hw6_3f.wav
视频时长: 89.27秒
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir C:\Users\Jerry\AppData\Local\VideoCaptioner\AppData\models C:\Users\Jerry\AppData\Local\Temp\bk_asr\tmpn88lpkrg\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.4 running on: CUDA
Starting to process: C:\Users\Jerry\AppData\Local\Temp\bk_asr\tmpn88lpkrg\audio.wav
Starting sequential faster-whisper inference.
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2324, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2191, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-30180:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1

### 日志信息（可选）| Logs (Optional)

```shell

```

**Comment by 104lexlin** [comment]
我自己是使用5070 Ti ，以目前狀況來說

**關於compute_type 參數**
我發現使用compute_type 參數只有float16, float32, bfloat16 這三個可以正常使用
其中，float32 執行最快，float16 次之，bfloat16 反而最慢，我也不知道原因

**關於vad_method**
如果使用vad_method 參數，預設是silero_v4_fw，也可以正常執行
但如果改為品質最好的pyannote_v3，則會報錯誤訊息

> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-07-30 更新:
如果vad_method 堅持要使用pyannote_v3 的話，可以加上以下判斷式，強制vad_device 使用CPU，但執行時間會拉長

1. 開啟VideoCaptioner\app\core\bk_asr\faster_whisper.py
2. 找到以下程式碼片段: 
```
if self.vad_method:
                cmd.extend(["--vad_method", self.vad_method])
```
改為
```
if self.vad_method:
                cmd.extend(["--vad_method", self.vad_method])
                if self.vad_method == "pyannote_v3":
                    cmd.extend(["--vad_device", "cpu"])
```

給有遇到同樣問題的人參考

**Comment by x923601616** [comment]
> 我自己正在使用5070 Ti，就目前情况来说
> 
> 关于compute_type参数 我发现使用compute_type参数只有float16, float32, bfloat16这三个可以正常使用 其中，float32执行最快，float16次之，bfloat16反而最慢，我也不知道原因
> 
> 关于vad_method 如果使用vad_method参数，默认是silero_v4_fw，也可以正常执行， 但如果改为质量最好的pyannote_v3，底部报错误 消息RuntimeError: CUDA error: no kernel image is available forexecution on the device CUDA内核错误可能会在其他一些API调用中异步报告，因此下面的堆栈跟踪可能不正确。 对于调试，请考虑传递 CUDA_LAUNCH_BLOCKING=1。 编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> 
> 给遇到同样问题的人参考

一样的显卡一样的问题

**Comment by heyang123mao** [comment]
牛啊，大佬！我一直转录失败！！！！

**Comment by AtmoOmen** [comment]
非常感谢, 5070TI 环境下可以正常运行了

**Comment by Xtiger909** [comment]
确实可以用了，跪谢！

**Comment by 123dfharefsd** [comment]
牛啊  我一直转录失败，5060 8G显卡。一直找不到原因。 用了你的方式成功了

**Comment by WEIFENG2333** [comment]
50系显卡转录错误的问题，接下来的1.4 版本将修复。

**Comment by heyang123mao** [comment]
> 50系显卡转录错误的问题，接下来的1.4 版本将修复。

太酷了大佬！期待更新

**Comment by prayjourney** [comment]
可以
