### ISSUE TITLE
无法正常使用显卡cuda运行任务

### ISSUE THREAD

**Issue by kingfc233** [WEIFENG2333/VideoCaptioner#809]
### 问题描述 | Problem Description

我的是5060ti 16g显卡，驱动版本580.97，cuda环境版本是12.1，在转录时只能用cpu运行，无法用cuda运行，一开始报错：An error occured while synchronizing the model Systran/faster-whisper-tiny from the Hugging Face Hub:。后来直接报错无信息了。
另外还有个问题，如何使用关键词？每次输入也是报错。不知道是格式还是组件问题。我希望将我的专业词汇加入纠正过程。

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：2025-09-12 19:59:41.244958
开始转换音频
转换为音频执行命令: ffmpeg -i D:\FFOutput\111.m4a -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\Administrator\AppData\Local\Temp\tmpdw01nt1m.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v3 --print_progress --model_dir D:\AI\卡卡字幕助手\VideoCaptioner\AppData\models C:\Users\Administrator\AppData\Local\Temp\bk_asr\tmp5aicjk93\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.01 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Starting sequential inference to transcribe: C:\Users\Administrator\AppData\Local\Temp\bk_asr\tmp5aicjk93\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-33960:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-09-12 19:59:53 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-09-12 19:59:53 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\AI\卡卡字幕助手\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\AI\卡卡字幕助手\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\卡卡字幕助手\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\卡卡字幕助手\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError
```

**Comment by kingfc233** [comment]
修改精度为float16后可以正常运行，GPU拉满了，CPU基本没工作，转录速度很慢，一个半小时的音频要用10-20分钟。但是同样的音频之前用FunClip只要2-3分钟，请问如何优化？

**Comment by kingfc233** [comment]
> 修改精度为float16后可以正常运行，GPU拉满了，CPU基本没工作，转录速度很慢，一个半小时的音频要用10-20分钟。但是同样的音频之前用FunClip只要2-3分钟，请问如何优化？

模型是Fast Whiser的large-v2，运行设备cuda，VAD是slero_v4，没开人声分离和单字时间戳等其他附加功能

**Comment by lex0301** [comment]
**1. 調整轉錄計算精度**
RTX 5000 系顯卡計算精度改float32 反而會快一點，前提是您的VRAM 足夠，至於為什麼比float16 快，我也不知道原因? 但個人實測結果就是這樣
另外，小弟使用RTX 5070Ti 16GB 顯卡，轉錄一個半小時的音源一樣差不多是10~20 分鐘不等
(根據對話內容多寡決定，不完全跟音源時長有關)

**2. 改用批次推理模式**
FastWhiser 可以使用批次推理模式，可以提高轉錄速度2-4倍，但轉錄品質可能會下降。
(GPU 使用率會吃滿，但轉錄品質小弟個人覺得無法接受)
請自行加入`cmd.extend(["--batched", "true"])` 
並搭配`cmd.extend(["--batch_size, "8"])`
(設定使用批次推理模式 ( --batched ) 時對模型的最大並行請求數。預設值： 8)

**3. 使用其他模型**
因為您沒有說明轉錄的語言，小弟只能從個人使用經驗上給予建議
假設是中文，那國內幾個ASR 模型確實速度跟結果品質都比較好，只是時間軸對齊上比較有問題
然後就是輸出都是長句，後續分割為短句後一樣要面對時間軸對齊問題
如果您不在意上述議題，個人可以建議您使用[Nosub](https://github.com/patui/Nosub)，搭配它可選用的國內本地開源模型進行轉錄
這裡有[說明](https://nosub.net/posts/p/261)

但如果是英文，FastWhiser 在速度及結果品質等綜合考量上已經是本地開源模型中前幾名了，模型使用large-v3-turbo 或distil-large-v3.5 (模型名稱有distil 字樣都是僅限於英文) 可以有效提升轉錄速度
HuggingFace 上有更多更好的開源模型
例如NVIDIA 的開源模型會更好，但您需要自己寫程式處理，可以參考該模型的範例程式，自己改寫

其他常用外語部分(日文、韓文、西班牙文之類的)，如果可以接受轉錄字幕的品質稍微降低，模型可以使用large-v3-turbo，轉錄速度也會提升。但目前在轉錄速度、結果品質、斷句、時間軸對齊等綜合考量上，最好的本地開源模型依然是large-v2

**4. 其他備註**
以下功能請根據您要轉錄的音源情境決定使用方式:
- 人聲分離功能是為了有背景噪音或背景音樂的情境下才需要開啟
- VAD 是為了讓字幕的時間軸對齊更準確，Fast Whiser 預設使用的是silero_v4_fw，已經是品質較佳且快的了，我自己是使用pyannote_v3 (RTX 5000 系顯卡不支援，vad_device 只能指定CPU)，犧牲轉錄速度換更準確的時間軸對齊

**Comment by philpw99** [comment]
> 修改精度为float16后可以正常运行，GPU拉满了，CPU基本没工作，转录速度很慢，一个半小时的音频要用10-20分钟。但是同样的音频之前用FunClip只要2-3分钟，请问如何优化？

rtx5000 系列要改成float32，而不是float16

**Comment by WEIFENG2333** [comment]
50系显卡转录错误的问题，接下来的1.4 版本将修复。

**Comment by iioSnail** [comment]
> 修改精度为float16后可以正常运行，GPU拉满了，CPU基本没工作，转录速度很慢，一个半小时的音频要用10-20分钟。但是同样的音频之前用FunClip只要2-3分钟，请问如何优化？

修改精度方式：
打开 VideoCaptioner\app\core\bk_asr\faster_whisper.py文件，找到128行左右，增加如下代码：

```
# 基本参数
cmd.extend(
    [
        str(audio_path),
        "-l",
        self.language,
        "-d",
        self.device,
        "--output_format",
        self.output_format,
        "--compute_type float16",   // 增加这行代码
    ]
)
```
