### ISSUE TITLE
转录失败：提示输出文件不存在

### ISSUE THREAD

**Issue by Font8036** [WEIFENG2333/VideoCaptioner#838]
### 🤔 问题描述 Problem Description

===========转录任务开始===========
时间：2025-10-06 16:46:50.174391
开始转换音频
转换为音频执行命令: ffmpeg -i D:\学习资源（伪）\迅雷下载暂存\CKK-002.avi -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\ZZZ\AppData\Local\Temp\tmpxmo_u5le.wav
视频时长: 7285.65秒
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir C:\Disk\C\application\VideoCaptioner\AppData\models C:\Users\ZZZ\AppData\Local\Temp\bk_asr\tmp4gclrkxe\audio.wav -l ja -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --ff_mdx_kim2 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Audio filtering is in progress...
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 0/486 | 00:00<<?
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 1/486 | 00:05<<44:04
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 2/486 | 00:05<<18:49
MDX Kim_Vocal_2 model probably is running on CUDA:   1% | 3/486 | 00:05<<10:46
MDX Kim_Vocal_2 model probably is running on CUDA:   1% | 4/486 | 00:05<<06:59
MDX Kim_Vocal_2 model probably is running on CUDA:   1% | 5/486 | 00:06<<04:54
MDX Kim_Vocal_2 model probably is running on CUDA:   1% | 6/486 | 00:06<<03:39
MDX Kim_Vocal_2 model probably is running on CUDA:   1% | 7/486 | 00:06<<02:51
MDX Kim_Vocal_2 model probably is running on CUDA:   2% | 8/486 | 00:06<<02:20
MDX Kim_Vocal_2 model probably is running on CUDA:   2% | 9/486 | 00:06<<01:59
MDX Kim_Vocal_2 model probably is running on CUDA:   2% | 10/486 | 00:06<<01:44
MDX Kim_Vocal_2 model probably is running on CUDA:   2% | 11/486 | 00:06<<01:34
MDX Kim_Vocal_2 model probably is running on CUDA:   2% | 12/486 | 00:07<<01:28
MDX Kim_Vocal_2 model probably is running on CUDA:   3% | 13/486 | 00:07<<01:23
MDX Kim_Vocal_2 model probably is running on CUDA:   3% | 14/486 | 00:07<<01:19
MDX Kim_Vocal_2 model probably is running on CUDA:   3% | 15/486 | 00:07<<01:17
MDX Kim_Vocal_2 model probably is running on CUDA:   3% | 16/486 | 00:07<<01:15
MDX Kim_Vocal_2 model probably is running on CUDA:   3% | 17/486 | 00:07<<01:14
MDX Kim_Vocal_2 model probably is running on CUDA:   4% | 18/486 | 00:08<<01:13
MDX Kim_Vocal_2 model probably is running on CUDA:   4% | 19/486 | 00:08<<01:13
MDX Kim_Vocal_2 model probably is running on CUDA:   4% | 20/486 | 00:08<<01:13
MDX Kim_Vocal_2 model probably is running on CUDA:   4% | 21/486 | 00:08<<01:12
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 22/486 | 00:08<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 23/486 | 00:08<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 24/486 | 00:08<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 25/486 | 00:09<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   5% | 26/486 | 00:09<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 27/486 | 00:09<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 28/486 | 00:09<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 29/486 | 00:09<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 30/486 | 00:09<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 31/486 | 00:10<<01:09
MDX Kim_Vocal_2 model probably is running on CUDA:   7% | 32/486 | 00:10<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   7% | 33/486 | 00:10<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   7% | 34/486 | 00:10<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   7% | 35/486 | 00:10<<01:09
MDX Kim_Vocal_2 model probably is running on CUDA:   7% | 36/486 | 00:10<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   8% | 37/486 | 00:11<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   8% | 38/486 | 00:11<<01:11
MDX Kim_Vocal_2 model probably is running on CUDA:   8% | 39/486 | 00:11<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   8% | 40/486 | 00:11<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   8% | 41/486 | 00:11<<01:10
MDX Kim_Vocal_2 model probably is running on CUDA:   9% | 42/486 | 00:11<<01:09
MDX Kim_Vocal_2 model probably is running on CUDA:   9% | 43/486 | 00:11<<01:08
MDX Kim_Vocal_2 model probably is running on CUDA:   9% | 44/486 | 00:12<<01:08
MDX Kim_Vocal_2 model probably is running on CUDA:   9% | 45/486 | 00:12<<01:08
MDX Kim_Vocal_2 model probably is running on CUDA:   9% | 46/486 | 00:12<<01:08
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 47/486 | 00:12<<01:07
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 48/486 | 00:12<<01:08
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 49/486 | 00:12<<01:07
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 50/486 | 00:13<<01:07
MDX Kim_Vocal_2 model probably is running on CUDA:  10% | 51/486 | 00:13<<01:07
MDX Kim_Vocal_2 model probably is running on CUDA:  11% | 52/486 | 00:13<<01:07
MDX Kim_Vocal_2 model probably is running on CUDA:  11% | 53/486 | 00:13<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  11% | 54/486 | 00:13<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  11% | 55/486 | 00:13<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  12% | 56/486 | 00:13<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  12% | 57/486 | 00:14<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  12% | 58/486 | 00:14<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  12% | 59/486 | 00:14<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  12% | 60/486 | 00:14<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  13% | 61/486 | 00:14<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  13% | 62/486 | 00:14<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  13% | 63/486 | 00:15<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  13% | 64/486 | 00:15<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  13% | 65/486 | 00:15<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  14% | 66/486 | 00:15<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  14% | 67/486 | 00:15<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  14% | 68/486 | 00:15<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  14% | 69/486 | 00:15<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  14% | 70/486 | 00:16<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 71/486 | 00:16<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 72/486 | 00:16<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 73/486 | 00:16<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 74/486 | 00:16<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  15% | 75/486 | 00:16<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  16% | 76/486 | 00:17<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  16% | 77/486 | 00:17<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  16% | 78/486 | 00:17<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  16% | 79/486 | 00:17<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  16% | 80/486 | 00:17<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 81/486 | 00:17<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 82/486 | 00:18<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 83/486 | 00:18<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 84/486 | 00:18<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 85/486 | 00:18<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  18% | 86/486 | 00:18<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  18% | 87/486 | 00:18<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  18% | 88/486 | 00:18<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  18% | 89/486 | 00:19<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  19% | 90/486 | 00:19<<01:06
MDX Kim_Vocal_2 model probably is running on CUDA:  19% | 91/486 | 00:19<<01:05
MDX Kim_Vocal_2 model probably is running on CUDA:  19% | 92/486 | 00:19<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  19% | 93/486 | 00:19<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  19% | 94/486 | 00:19<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 95/486 | 00:20<<01:04
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 96/486 | 00:20<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 97/486 | 00:20<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 98/486 | 00:20<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  20% | 99/486 | 00:20<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  21% | 100/486 | 00:20<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  21% | 101/486 | 00:21<<01:03
MDX Kim_Vocal_2 model probably is running on CUDA:  21% | 102/486 | 00:21<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  21% | 103/486 | 00:21<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  21% | 104/486 | 00:21<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 105/486 | 00:21<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 106/486 | 00:21<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 107/486 | 00:22<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 108/486 | 00:22<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 109/486 | 00:22<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  23% | 110/486 | 00:22<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  23% | 111/486 | 00:22<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  23% | 112/486 | 00:22<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  23% | 113/486 | 00:23<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  23% | 114/486 | 00:23<<01:02
MDX Kim_Vocal_2 model probably is running on CUDA:  24% | 115/486 | 00:23<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  24% | 116/486 | 00:23<<01:01
MDX Kim_Vocal_2 model probably is running on CUDA:  24% | 117/486 | 00:23<<00:59
MDX Kim_Vocal_2 model probably is running on CUDA:  24% | 118/486 | 00:23<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  24% | 119/486 | 00:24<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 120/486 | 00:24<<00:59
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 121/486 | 00:24<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 122/486 | 00:24<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  25% | 123/486 | 00:24<<00:59
MDX Kim_Vocal_2 model probably is running on CUDA:  26% | 124/486 | 00:24<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  26% | 125/486 | 00:25<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  26% | 126/486 | 00:25<<00:58
MDX Kim_Vocal_2 model probably is running on CUDA:  26% | 127/486 | 00:25<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  26% | 128/486 | 00:25<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  27% | 129/486 | 00:25<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  27% | 130/486 | 00:25<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  27% | 131/486 | 00:25<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  27% | 132/486 | 00:26<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  27% | 133/486 | 00:26<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 134/486 | 00:26<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 135/486 | 00:26<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 136/486 | 00:26<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 137/486 | 00:26<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 138/486 | 00:27<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  29% | 139/486 | 00:27<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  29% | 140/486 | 00:27<<00:57
MDX Kim_Vocal_2 model probably is running on CUDA:  29% | 141/486 | 00:27<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  29% | 142/486 | 00:27<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  29% | 143/486 | 00:27<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 144/486 | 00:28<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 145/486 | 00:28<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 146/486 | 00:28<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 147/486 | 00:28<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  30% | 148/486 | 00:28<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  31% | 149/486 | 00:28<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  31% | 150/486 | 00:29<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  31% | 151/486 | 00:29<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  31% | 152/486 | 00:29<<00:56
MDX Kim_Vocal_2 model probably is running on CUDA:  31% | 153/486 | 00:29<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  32% | 154/486 | 00:29<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  32% | 155/486 | 00:29<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  32% | 156/486 | 00:30<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  32% | 157/486 | 00:30<<00:54
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 158/486 | 00:30<<00:55
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 159/486 | 00:30<<00:54
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 160/486 | 00:30<<00:54
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 161/486 | 00:30<<00:54
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 162/486 | 00:31<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  34% | 163/486 | 00:31<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  34% | 164/486 | 00:31<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  34% | 165/486 | 00:31<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  34% | 166/486 | 00:31<<00:52
MDX Kim_Vocal_2 model probably is running on CUDA:  34% | 167/486 | 00:31<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 168/486 | 00:32<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 169/486 | 00:32<<00:52
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 170/486 | 00:32<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 171/486 | 00:32<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  35% | 172/486 | 00:32<<00:52
MDX Kim_Vocal_2 model probably is running on CUDA:  36% | 173/486 | 00:32<<00:53
MDX Kim_Vocal_2 model probably is running on CUDA:  36% | 174/486 | 00:33<<00:52
MDX Kim_Vocal_2 model probably is running on CUDA:  36% | 175/486 | 00:33<<00:51
MDX Kim_Vocal_2 model probably is running on CUDA:  36% | 176/486 | 00:33<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  36% | 177/486 | 00:33<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  37% | 178/486 | 00:33<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  37% | 179/486 | 00:33<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  37% | 180/486 | 00:34<<00:48
MDX Kim_Vocal_2 model probably is running on CUDA:  37% | 181/486 | 00:34<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  37% | 182/486 | 00:34<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  38% | 183/486 | 00:34<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  38% | 184/486 | 00:34<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  38% | 185/486 | 00:34<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  38% | 186/486 | 00:35<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  38% | 187/486 | 00:35<<00:51
MDX Kim_Vocal_2 model probably is running on CUDA:  39% | 188/486 | 00:35<<00:50
MDX Kim_Vocal_2 model probably is running on CUDA:  39% | 189/486 | 00:35<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  39% | 190/486 | 00:35<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  39% | 191/486 | 00:35<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 192/486 | 00:36<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 193/486 | 00:36<<00:49
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 194/486 | 00:36<<00:47
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 195/486 | 00:36<<00:47
MDX Kim_Vocal_2 model probably is running on CUDA:  40% | 196/486 | 00:36<<00:46
MDX Kim_Vocal_2 model probably is running on CUDA:  41% | 197/486 | 00:36<<00:46
MDX Kim_Vocal_2 model probably is running on CUDA:  41% | 198/486 | 00:37<<00:45
MDX Kim_Vocal_2 model probably is running on CUDA:  41% | 199/486 | 00:37<<00:45
MDX Kim_Vocal_2 model probably is running on CUDA:  41% | 200/486 | 00:37<<00:45
MDX Kim_Vocal_2 model probably is running on CUDA:  41% | 201/486 | 00:37<<00:46
MDX Kim_Vocal_2 model probably is running on CUDA:  42% | 202/486 | 00:37<<00:46
MDX Kim_Vocal_2 model probably is running on CUDA:  42% | 203/486 | 00:37<<00:46
MDX Kim_Vocal_2 model probably is running on CUDA:  42% | 204/486 | 00:38<<00:45
MDX Kim_Vocal_2 model probably is running on CUDA:  42% | 205/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  42% | 206/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  43% | 207/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  43% | 208/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  43% | 209/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  43% | 210/486 | 00:38<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  43% | 211/486 | 00:39<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 212/486 | 00:39<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 213/486 | 00:39<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 214/486 | 00:39<<00:44
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 215/486 | 00:39<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 216/486 | 00:39<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 217/486 | 00:40<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 218/486 | 00:40<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 219/486 | 00:40<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 220/486 | 00:40<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  45% | 221/486 | 00:40<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  46% | 222/486 | 00:40<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  46% | 223/486 | 00:41<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  46% | 224/486 | 00:41<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  46% | 225/486 | 00:41<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  47% | 226/486 | 00:41<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  47% | 227/486 | 00:41<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  47% | 228/486 | 00:41<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  47% | 229/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  47% | 230/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  48% | 231/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  48% | 232/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  48% | 233/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  48% | 234/486 | 00:42<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  48% | 235/486 | 00:43<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  49% | 236/486 | 00:43<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  49% | 237/486 | 00:43<<00:42
MDX Kim_Vocal_2 model probably is running on CUDA:  49% | 238/486 | 00:43<<00:43
MDX Kim_Vocal_2 model probably is running on CUDA:  49% | 239/486 | 00:43<<00:41
MDX Kim_Vocal_2 model probably is running on CUDA:  49% | 240/486 | 00:43<<00:40
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 241/486 | 00:44<<00:39
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 242/486 | 00:44<<00:39
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 243/486 | 00:44<<00:39
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 244/486 | 00:44<<00:38
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 245/486 | 00:44<<00:38
MDX Kim_Vocal_2 model probably is running on CUDA:  51% | 246/486 | 00:44<<00:38
MDX Kim_Vocal_2 model probably is running on CUDA:  51% | 247/486 | 00:44<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  51% | 248/486 | 00:45<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  51% | 249/486 | 00:45<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  51% | 250/486 | 00:45<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  52% | 251/486 | 00:45<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  52% | 252/486 | 00:45<<00:37
MDX Kim_Vocal_2 model probably is running on CUDA:  52% | 253/486 | 00:45<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  52% | 254/486 | 00:46<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  52% | 255/486 | 00:46<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  53% | 256/486 | 00:46<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  53% | 257/486 | 00:46<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  53% | 258/486 | 00:46<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  53% | 259/486 | 00:46<<00:35
MDX Kim_Vocal_2 model probably is running on CUDA:  53% | 260/486 | 00:47<<00:35
MDX Kim_Vocal_2 model probably is running on CUDA:  54% | 261/486 | 00:47<<00:35
MDX Kim_Vocal_2 model probably is running on CUDA:  54% | 262/486 | 00:47<<00:35
MDX Kim_Vocal_2 model probably is running on CUDA:  54% | 263/486 | 00:47<<00:35
MDX Kim_Vocal_2 model probably is running on CUDA:  54% | 264/486 | 00:47<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 265/486 | 00:47<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 266/486 | 00:47<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 267/486 | 00:48<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 268/486 | 00:48<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  55% | 269/486 | 00:48<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 270/486 | 00:48<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 271/486 | 00:48<<00:34
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 272/486 | 00:48<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 273/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 274/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  57% | 275/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  57% | 276/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  57% | 277/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  57% | 278/486 | 00:49<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  57% | 279/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  58% | 280/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  58% | 281/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  58% | 282/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  58% | 283/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  58% | 284/486 | 00:50<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  59% | 285/486 | 00:51<<00:33
MDX Kim_Vocal_2 model probably is running on CUDA:  59% | 286/486 | 00:51<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  59% | 287/486 | 00:51<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  59% | 288/486 | 00:51<<00:32
MDX Kim_Vocal_2 model probably is running on CUDA:  59% | 289/486 | 00:51<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 290/486 | 00:51<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 291/486 | 00:51<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 292/486 | 00:52<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 293/486 | 00:52<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  60% | 294/486 | 00:52<<00:31
MDX Kim_Vocal_2 model probably is running on CUDA:  61% | 295/486 | 00:52<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  61% | 296/486 | 00:52<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  61% | 297/486 | 00:52<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  61% | 298/486 | 00:53<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  62% | 299/486 | 00:53<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  62% | 300/486 | 00:53<<00:29
MDX Kim_Vocal_2 model probably is running on CUDA:  62% | 301/486 | 00:53<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  62% | 302/486 | 00:53<<00:30
MDX Kim_Vocal_2 model probably is running on CUDA:  62% | 303/486 | 00:53<<00:29
MDX Kim_Vocal_2 model probably is running on CUDA:  63% | 304/486 | 00:54<<00:29
MDX Kim_Vocal_2 model probably is running on CUDA:  63% | 305/486 | 00:54<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  63% | 306/486 | 00:54<<00:29
MDX Kim_Vocal_2 model probably is running on CUDA:  63% | 307/486 | 00:54<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  63% | 308/486 | 00:54<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  64% | 309/486 | 00:54<<00:27
MDX Kim_Vocal_2 model probably is running on CUDA:  64% | 310/486 | 00:55<<00:27
MDX Kim_Vocal_2 model probably is running on CUDA:  64% | 311/486 | 00:55<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  64% | 312/486 | 00:55<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  64% | 313/486 | 00:55<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 314/486 | 00:55<<00:28
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 315/486 | 00:55<<00:27
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 316/486 | 00:56<<00:27
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 317/486 | 00:56<<00:27
MDX Kim_Vocal_2 model probably is running on CUDA:  65% | 318/486 | 00:56<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  66% | 319/486 | 00:56<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  66% | 320/486 | 00:56<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  66% | 321/486 | 00:56<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  66% | 322/486 | 00:56<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  66% | 323/486 | 00:57<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 324/486 | 00:57<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 325/486 | 00:57<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 326/486 | 00:57<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 327/486 | 00:57<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 328/486 | 00:57<<00:26
MDX Kim_Vocal_2 model probably is running on CUDA:  68% | 329/486 | 00:58<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  68% | 330/486 | 00:58<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  68% | 331/486 | 00:58<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  68% | 332/486 | 00:58<<00:24
MDX Kim_Vocal_2 model probably is running on CUDA:  69% | 333/486 | 00:58<<00:24
MDX Kim_Vocal_2 model probably is running on CUDA:  69% | 334/486 | 00:58<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  69% | 335/486 | 00:59<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  69% | 336/486 | 00:59<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  69% | 337/486 | 00:59<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 338/486 | 00:59<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 339/486 | 00:59<<00:25
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 340/486 | 00:59<<00:24
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 341/486 | 01:00<<00:24
MDX Kim_Vocal_2 model probably is running on CUDA:  70% | 342/486 | 01:00<<00:23
MDX Kim_Vocal_2 model probably is running on CUDA:  71% | 343/486 | 01:00<<00:23
MDX Kim_Vocal_2 model probably is running on CUDA:  71% | 344/486 | 01:00<<00:23
MDX Kim_Vocal_2 model probably is running on CUDA:  71% | 345/486 | 01:00<<00:23
MDX Kim_Vocal_2 model probably is running on CUDA:  71% | 346/486 | 01:00<<00:23
MDX Kim_Vocal_2 model probably is running on CUDA:  71% | 347/486 | 01:01<<00:22
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 348/486 | 01:01<<00:22
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 349/486 | 01:01<<00:22
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 350/486 | 01:01<<00:22
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 351/486 | 01:01<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 352/486 | 01:01<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  73% | 353/486 | 01:02<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  73% | 354/486 | 01:02<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  73% | 355/486 | 01:02<<00:21
MDX Kim_Vocal_2 model probably is running on CUDA:  73% | 356/486 | 01:02<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  73% | 357/486 | 01:02<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  74% | 358/486 | 01:02<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  74% | 359/486 | 01:03<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  74% | 360/486 | 01:03<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  74% | 361/486 | 01:03<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  74% | 362/486 | 01:03<<00:20
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 363/486 | 01:03<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 364/486 | 01:03<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 365/486 | 01:04<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  75% | 366/486 | 01:04<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  76% | 367/486 | 01:04<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  76% | 368/486 | 01:04<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  76% | 369/486 | 01:04<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  76% | 370/486 | 01:04<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  76% | 371/486 | 01:04<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  77% | 372/486 | 01:05<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  77% | 373/486 | 01:05<<00:19
MDX Kim_Vocal_2 model probably is running on CUDA:  77% | 374/486 | 01:05<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  77% | 375/486 | 01:05<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  77% | 376/486 | 01:05<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 377/486 | 01:06<<00:18
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 378/486 | 01:06<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 379/486 | 01:06<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 380/486 | 01:06<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 381/486 | 01:06<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  79% | 382/486 | 01:06<<00:16
MDX Kim_Vocal_2 model probably is running on CUDA:  79% | 383/486 | 01:06<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  79% | 384/486 | 01:07<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  79% | 385/486 | 01:07<<00:16
MDX Kim_Vocal_2 model probably is running on CUDA:  79% | 386/486 | 01:07<<00:17
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 387/486 | 01:07<<00:16
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 388/486 | 01:07<<00:16
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 389/486 | 01:07<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 390/486 | 01:08<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  80% | 391/486 | 01:08<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  81% | 392/486 | 01:08<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  81% | 393/486 | 01:08<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  81% | 394/486 | 01:08<<00:15
MDX Kim_Vocal_2 model probably is running on CUDA:  81% | 395/486 | 01:08<<00:14
MDX Kim_Vocal_2 model probably is running on CUDA:  81% | 396/486 | 01:09<<00:14
MDX Kim_Vocal_2 model probably is running on CUDA:  82% | 397/486 | 01:09<<00:14
MDX Kim_Vocal_2 model probably is running on CUDA:  82% | 398/486 | 01:09<<00:14
MDX Kim_Vocal_2 model probably is running on CUDA:  82% | 399/486 | 01:09<<00:14
MDX Kim_Vocal_2 model probably is running on CUDA:  82% | 400/486 | 01:09<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 401/486 | 01:09<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 402/486 | 01:10<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 403/486 | 01:10<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 404/486 | 01:10<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 405/486 | 01:10<<00:13
MDX Kim_Vocal_2 model probably is running on CUDA:  84% | 406/486 | 01:10<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  84% | 407/486 | 01:10<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  84% | 408/486 | 01:11<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  84% | 409/486 | 01:11<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  84% | 410/486 | 01:11<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 411/486 | 01:11<<00:12
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 412/486 | 01:11<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 413/486 | 01:11<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 414/486 | 01:12<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  85% | 415/486 | 01:12<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  86% | 416/486 | 01:12<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  86% | 417/486 | 01:12<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  86% | 418/486 | 01:12<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  86% | 419/486 | 01:12<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  86% | 420/486 | 01:12<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  87% | 421/486 | 01:13<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  87% | 422/486 | 01:13<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  87% | 423/486 | 01:13<<00:10
MDX Kim_Vocal_2 model probably is running on CUDA:  87% | 424/486 | 01:13<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  87% | 425/486 | 01:13<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  88% | 426/486 | 01:13<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  88% | 427/486 | 01:14<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  88% | 428/486 | 01:14<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  88% | 429/486 | 01:14<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  88% | 430/486 | 01:14<<00:09
MDX Kim_Vocal_2 model probably is running on CUDA:  89% | 431/486 | 01:14<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  89% | 432/486 | 01:14<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  89% | 433/486 | 01:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  89% | 434/486 | 01:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 435/486 | 01:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 436/486 | 01:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 437/486 | 01:15<<00:08
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 438/486 | 01:15<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  90% | 439/486 | 01:16<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  91% | 440/486 | 01:16<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  91% | 441/486 | 01:16<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  91% | 442/486 | 01:16<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  91% | 443/486 | 01:16<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  91% | 444/486 | 01:16<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  92% | 445/486 | 01:17<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  92% | 446/486 | 01:17<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  92% | 447/486 | 01:17<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  92% | 448/486 | 01:17<<00:06
MDX Kim_Vocal_2 model probably is running on CUDA:  92% | 449/486 | 01:17<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  93% | 450/486 | 01:17<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  93% | 451/486 | 01:17<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  93% | 452/486 | 01:18<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  93% | 453/486 | 01:18<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  93% | 454/486 | 01:18<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 455/486 | 01:18<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 456/486 | 01:18<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 457/486 | 01:18<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 458/486 | 01:19<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 459/486 | 01:19<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 460/486 | 01:19<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 461/486 | 01:19<<00:04
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 462/486 | 01:19<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 463/486 | 01:19<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  95% | 464/486 | 01:20<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  96% | 465/486 | 01:20<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  96% | 466/486 | 01:20<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  96% | 467/486 | 01:20<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  96% | 468/486 | 01:20<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  97% | 469/486 | 01:20<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  97% | 470/486 | 01:21<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  97% | 471/486 | 01:21<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  97% | 472/486 | 01:21<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  97% | 473/486 | 01:21<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  98% | 474/486 | 01:21<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  98% | 475/486 | 01:21<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  98% | 476/486 | 01:21<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  98% | 477/486 | 01:22<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  98% | 478/486 | 01:22<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 479/486 | 01:22<<00:01
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 480/486 | 01:22<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 481/486 | 01:22<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 482/486 | 01:22<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 483/486 | 01:23<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 484/486 | 01:23<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 485/486 | 01:23<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 486/486 | 01:23<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 486/486 | 01:24<<00:00
Starting sequential inference to transcribe: C:\Users\ZZZ\AppData\Local\Temp\bk_asr\tmp4gclrkxe\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-28756:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-10-06 16:48:50 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\ZZZ\AppData\Local\Temp\bk_asr\tmp4gclrkxe\audio.srt
Traceback (most recent call last):
  File "C:\Disk\C\application\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "C:\Disk\C\application\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Disk\C\application\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Disk\C\application\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
    raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\ZZZ\AppData\Local\Temp\bk_asr\tmp4gclrkxe\audio.srt

**Comment by elan5460** [comment]
遇到相同问题，这个怎么有解决办法吗？

**Comment by hookgogo** [comment]
> 遇到相同问题，这个怎么有解决办法吗？

我也遇到相同问题，想联系创作者解决

**Comment by wuxiansheng2375** [comment]
我也遇到相同得问题

**Comment by hookgogo** [comment]
问题已经解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年10月18日(周六) 晚上10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 转录失败：提示输出文件不存在 (Issue #838)


wuxiansheng2375 left a comment (WEIFENG2333/VideoCaptioner#838)
 
我也遇到相同得问题

**Comment by philpw99** [comment]
`RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED`
用 #814 的解决办法

**Comment by WEIFENG2333** [comment]
50系显卡转录错误的问题，接下来的1.4 版本将修复~
