### ISSUE TITLE
FasterWhisper语音转录报错

### ISSUE THREAD

**Issue by lin1993** [WEIFENG2333/VideoCaptioner#900]
### 问题描述 | Problem Description

5070ti显卡 用 large-v2和v3 v3-tb模型都尝试了只有报错信息 另外就是报错以后没法清空任务重新拖进来提示当前任务还没结束
后面有日志

<img width="1371" height="858" alt="Image" src="https://github.com/user-attachments/assets/8015d2bd-55dd-4890-9e86-51d599e9cd2f" />

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：2025-11-29 23:44:46.347803
开始转换音频
转换为音频执行命令: ffmpeg -i E:\ai\index-tts\outputs\spk_1764426270.wav -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\xxxx\AppData\Local\Temp\tmpkqw49zvw.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v3-turbo --print_progress --model_dir D:\program\VideoCaptioner\AppData\models C:\Users\xxxx\AppData\Local\Temp\bk_asr\tmpvof7t00c\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Starting sequential inference to transcribe: C:\Users\xxxx\AppData\Local\Temp\bk_asr\tmpvof7t00c\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-30800:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-11-29 23:44:49 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-11-29 23:44:49 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\program\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError
```

**Comment by lin1993** [comment]
===========转录任务开始===========
时间：2025-11-29 23:51:01.532619
开始转换音频
转换为音频执行命令: ffmpeg -i E:\ai\index-tts\outputs\spk_1764426270.wav -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\xxxx\AppData\Local\Temp\tmpyfpetjj5.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir D:\program\VideoCaptioner\AppData\models C:\Users\xxxx\AppData\Local\Temp\bk_asr\tmpryx1ucmq\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\xxxx\AppData\Local\Temp\bk_asr\tmpryx1ucmq\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-43416:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-11-29 23:51:06 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-11-29 23:51:06 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\program\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError
补充用large-v2模型的转换

**Comment by lin1993** [comment]
===========转录任务开始===========
时间：2025-11-29 23:53:02.780585
开始转换音频
转换为音频执行命令: ffmpeg -i E:\ai\index-tts\outputs\spk_1764426270.wav -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\xxx\AppData\Local\Temp\tmp8zjbq786.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m tiny --print_progress --model_dir D:\program\VideoCaptioner\AppData\models C:\Users\xxx\AppData\Local\Temp\bk_asr\tmped9yg405\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Model not found at: D:\program\VideoCaptioner\AppData\models\faster-whisper-tiny
Attempting to download:
vocabulary.txt: 0.00B [00:00, ?B/s]
vocabulary.txt: 274kB [00:00, 1.79MB/s]
vocabulary.txt: 460kB [00:00, 1.53MB/s]
vocabulary.txt: 460kB [00:00, 1.57MB/s]
model.bin:   0%|          | 0.00/75.5M [00:00<?, ?B/s]
config.json: 0.00B [00:00, ?B/s][A
config.json: 2.25kB [00:00, 4.45MB/s]
tokenizer.json: 0.00B [00:00, ?B/s][A
tokenizer.json: 865kB [00:00, 2.55MB/s][A
tokenizer.json: 1.56MB [00:00, 2.76MB/s][A
tokenizer.json: 2.20MB [00:01, 1.93MB/s][A
tokenizer.json: 2.20MB [00:01, 2.10MB/s]
model.bin:  14%|        | 10.5M/75.5M [00:12<01:17, 834kB/s]
model.bin:  28%|       | 21.0M/75.5M [00:22<00:56, 959kB/s]
model.bin:  42%|     | 31.5M/75.5M [00:24<00:29, 1.49MB/s]
model.bin:  56%|    | 41.9M/75.5M [00:26<00:15, 2.17MB/s]
model.bin:  69%|   | 52.4M/75.5M [00:28<00:08, 2.60MB/s]
model.bin:  83%| | 62.9M/75.5M [00:31<00:04, 2.87MB/s]
model.bin:  97%|| 73.4M/75.5M [00:33<00:00, 3.44MB/s]
model.bin: 100%|| 75.5M/75.5M [00:33<00:00, 3.57MB/s]
model.bin: 100%|| 75.5M/75.5M [00:33<00:00, 2.23MB/s]
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\xxx\AppData\Local\Temp\bk_asr\tmped9yg405\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-39700:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-11-29 23:53:43 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\xxx\AppData\Local\Temp\bk_asr\tmped9yg405\audio.srt
Traceback (most recent call last):
  File "D:\program\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
    raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\xxx\AppData\Local\Temp\bk_asr\tmped9yg405\audio.srt

这个模型可以模型转换步骤可以 但是其它地方又报错了

**Comment by UM7lab** [comment]
5060 Laptop显卡也遇到了相似的问题，我在另一台4090电脑上测试了large-v3则可以正常运行
5060 Laptop的Log如下：
`
===========转录任务开始===========
时间：2025-11-29 23:47:12.850991
开始转换音频
转换为音频执行命令: ffmpeg -i C:\Users\um\Downloads\test-video.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\um\AppData\Local\Temp\tmpjqcofs59.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v3 --print_progress --model_dir C:\Programs\VideoCaptioner\AppData\models C:\Users\um\AppData\Local\Temp\bk_asr\tmpms32jwi_\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter false --ff_mdx_kim2 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Audio filtering is in progress...
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 0/18 | 00:00<<?
MDX Kim_Vocal_2 model probably is running on CUDA:   6% | 1/18 | 03:01<<51:17
MDX Kim_Vocal_2 model probably is running on CUDA:  11% | 2/18 | 03:01<<19:59
MDX Kim_Vocal_2 model probably is running on CUDA:  17% | 3/18 | 03:02<<10:16
MDX Kim_Vocal_2 model probably is running on CUDA:  22% | 4/18 | 03:03<<05:52
MDX Kim_Vocal_2 model probably is running on CUDA:  28% | 5/18 | 03:03<<03:32
MDX Kim_Vocal_2 model probably is running on CUDA:  33% | 6/18 | 03:04<<02:12
MDX Kim_Vocal_2 model probably is running on CUDA:  39% | 7/18 | 03:05<<01:24
MDX Kim_Vocal_2 model probably is running on CUDA:  44% | 8/18 | 03:06<<00:54
MDX Kim_Vocal_2 model probably is running on CUDA:  50% | 9/18 | 03:07<<00:36
MDX Kim_Vocal_2 model probably is running on CUDA:  56% | 10/18 | 03:07<<00:24
MDX Kim_Vocal_2 model probably is running on CUDA:  61% | 11/18 | 03:08<<00:16
MDX Kim_Vocal_2 model probably is running on CUDA:  67% | 12/18 | 03:09<<00:11
MDX Kim_Vocal_2 model probably is running on CUDA:  72% | 13/18 | 03:10<<00:07
MDX Kim_Vocal_2 model probably is running on CUDA:  78% | 14/18 | 03:10<<00:05
MDX Kim_Vocal_2 model probably is running on CUDA:  83% | 15/18 | 03:11<<00:03
MDX Kim_Vocal_2 model probably is running on CUDA:  89% | 16/18 | 03:12<<00:02
MDX Kim_Vocal_2 model probably is running on CUDA:  94% | 17/18 | 03:13<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 18/18 | 03:23<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 18/18 | 03:23<<00:00
Starting sequential inference to transcribe: C:\Users\um\AppData\Local\Temp\bk_asr\tmpms32jwi_\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-34036:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-11-29 23:51:11 - transcript_thread - ERROR - 转录过程中发生错误: Faster Whisper 输出文件不存在: C:\Users\um\AppData\Local\Temp\bk_asr\tmpms32jwi_\audio.srt
Traceback (most recent call last):
  File "C:\Programs\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "C:\Programs\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 270, in _run
    raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")
RuntimeError: Faster Whisper 输出文件不存在: C:\Users\um\AppData\Local\Temp\bk_asr\tmpms32jwi_\audio.srt
`
初步判定可能是软件的cuBLAS库可能过旧，没有包含对RTX50系显卡的Float16支持。

**Comment by fm1cc** [comment]
遇到此类情况，可以尝试修改在程序的安装目录下的

> \app\core\bk_asr\faster_whisper.py

找到

```
基本参数
cmd.extend(
...
...
self.output_format,
```

在最后添加两行

```
"--compute_type",
"float32",
```

保存后重启程序再尝试执行转录

**Comment by manisen2024** [comment]
> 遇到此类情况，可以尝试修改在程序的安装目录下的
> 
> > \app\core\bk_asr\faster_whisper.py
> 
> 找到
> 
> ```
> 基本参数
> cmd.extend(
> ...
> ...
> self.output_format,
> ```
> 
> 在最后添加两行
> 
> ```
> "--compute_type",
> "float32",
> ```
> 
> 保存后重启程序再尝试执行转录

厉害了，加了后就能用了

**Comment by lin1993** [comment]
> 遇到此类情况，可以尝试修改在程序的安装目录下的
> 
> > \App\core\bk_asr\faster_whisper.py
> 
> 找到
> 
> ```
> 基本参数
> cmd.extend(
> ...
> ...
> self.output_format,
> ```
> 
> 在最后添加两行
> 
> ```
> "--compute_type",
> "float32",
> ```
> 
> 保存后重启程序再尝试执行转录

牛逼牛逼 我试了 也可以了

**Comment by YHH-XQ** [comment]
> 遇到此类情况，可以尝试修改在程序的安装目录下的
> 
> > \app\core\bk_asr\faster_whisper.py
> 
> 找到
> 
> ```
> 基本参数
> cmd.extend(
> ...
> ...
> self.output_format,
> ```
> 
> 在最后添加两行
> 
> ```
> "--compute_type",
> "float32",
> ```
> 
> 保存后重启程序再尝试执行转录

牛逼
