### ISSUE TITLE
转录失败报错

### ISSUE THREAD

**Issue by LFeightyFour** [WEIFENG2333/VideoCaptioner#975]
### 问题描述 | Problem Description

跑测试视频，日志提示如下错误，请问可能是什么原因：

===========转录任务开始===========
时间：2026-01-24 23:35:03.717158
开始转换音频
转换为音频执行命令: ffmpeg -i C:\Users\Administrator\AppData\Local\VideoCaptioner\work-dir\TED经典：今晚DDL的你还在刷b站？【TED演讲】\TED经典：今晚DDL的你还在刷b站？【TED演讲】.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\Administrator\AppData\Local\Temp\tmpsdwr_xph.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir C:\Users\Administrator\AppData\Local\VideoCaptioner\AppData\models C:\Users\Administrator\AppData\Local\Temp\bk_asr\tmp0zjjzyw7\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 90 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\Administrator\AppData\Local\Temp\bk_asr\tmp0zjjzyw7\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-172880:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2026-01-24 23:35:13 - faster_whisper - ERROR - Faster Whisper 错误: 
2026-01-24 23:35:13 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError

### 日志信息（可选）| Logs (Optional)

```shell

```

**Comment by philpw99** [comment]
#814

**Comment by achao2026** [comment]
50系显卡吗？https://github.com/WEIFENG2333/VideoCaptioner/issues/900#issuecomment-3636189842

**Comment by dale1236** [comment]
我也是转录失败，用cuda就会这样，5060的，cpu可以正常转录

**Comment by LFeightyFour** [comment]
> 50系显卡吗？[#900 (comment)](https://github.com/WEIFENG2333/VideoCaptioner/issues/900#issuecomment-3636189842)

我是50系

**Comment by achao2026** [comment]
点我评论那个数字就是别人给出的解决方案。需要安装python的，用python修改就好。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年1月25日(周日) 上午9:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 转录失败报错 (Issue #975)


dale1236 left a comment (WEIFENG2333/VideoCaptioner#975)
 
我也是转录失败，用cuda就会这样，5060的，cpu可以正常转录

**Comment by LFeightyFour** [comment]
已解决，谢谢！

**Comment by dale1236** [comment]
> 点我评论那个数字就是别人给出的解决方案。需要安装python的，用python修改就好。
> […](#)

谢谢大佬
